<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FirawynixWindowManager</AssemblyName>
    <Version>0.3.2</Version>
    <ApplicationIcon>assets\celtic-knot-transparent.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="assets\celtic-knot-transparent.png" />
  </ItemGroup>
</Project>
